In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('car.csv')

In [3]:
data.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [4]:
data.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [5]:
def checking(data):
    l=[]
    columns=data.columns
    for col in columns:
        dtypes=data[col].dtypes
        nunique=data[col].nunique()
        sum_null=data[col].isnull().sum()
        l.append([col,dtypes,nunique,sum_null])
    new_df=pd.DataFrame(l)
    new_df.columns=['COLUMNS','DATA_TYPES','UNIQUE_VALUE','NULL?']
    return new_df

In [6]:
checking(data)

             COLUMNS DATA_TYPES  UNIQUE_VALUE  NULL?
0             car_ID      int64           205      0
1          symboling      int64             6      0
2            CarName     object           147      0
3           fueltype     object             2      0
4         aspiration     object             2      0
5         doornumber     object             2      0
6            carbody     object             5      0
7         drivewheel     object             3      0
8     enginelocation     object             2      0
9          wheelbase    float64            53      0
10         carlength    float64            75      0
11          carwidth    float64            44      0
12         carheight    float64            49      0
13        curbweight      int64           171      0
14        enginetype     object             7      0
15    cylindernumber     object             7      0
16        enginesize      int64            44      0
17        fuelsystem     object             8      0
18         boreratio    float64            38      0
19            stroke    float64            37      0
20  compressionratio    float64            32      0
21        horsepower      int64            59      0
22           peakrpm      int64            23      0
23           citympg      int64            29      0
24        highwaympg      int64            30      0
25             price    float64           189      0

In [7]:
len(data)

205

In [8]:
data.shape

(205, 26)

In [9]:
data.describe()

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

In [10]:
data.drop('car_ID',axis=1,inplace=True)

In [11]:
data.head()

,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [12]:
data['CarName']=data['CarName'].str.split(' ',expand=True)[0]

In [13]:
data.head()

,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,audi,gas,std,four,sedan,fwd,front,99.8,176.6,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,audi,gas,std,four,sedan,4wd,front,99.4,176.6,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [14]:
data['CarName'].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'maxda', 'mazda', 'buick', 'mercury',
       'mitsubishi', 'Nissan', 'nissan', 'peugeot', 'plymouth', 'porsche',
       'porcshce', 'renault', 'saab', 'subaru', 'toyota', 'toyouta',
       'vokswagen', 'volkswagen', 'vw', 'volvo'], dtype=object)

In [15]:
data['CarName'] = data['CarName'].replace({'maxda': 'mazda', 'nissan': 'Nissan', 'porcshce': 'porsche', 'toyouta': 'toyota', 
                            'vokswagen': 'volkswagen', 'vw': 'volkswagen'})

In [16]:
data['CarName'].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'buick', 'mercury', 'mitsubishi',
       'Nissan', 'peugeot', 'plymouth', 'porsche', 'renault', 'saab',
       'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

In [17]:
data['symboling']=data['symboling'].astype('str')

In [18]:
category_cols=data.select_dtypes(include=['object']).columns

In [19]:
data[category_cols].head()

,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,enginetype,cylindernumber,fuelsystem
0,3,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
1,3,alfa-romero,gas,std,two,convertible,rwd,front,dohc,four,mpfi
2,1,alfa-romero,gas,std,two,hatchback,rwd,front,ohcv,six,mpfi
3,2,audi,gas,std,four,sedan,fwd,front,ohc,four,mpfi
4,2,audi,gas,std,four,sedan,4wd,front,ohc,five,mpfi

In [20]:
data[category_cols].shape

(205, 11)

In [21]:
from sklearn.preprocessing import LabelEncoder
def encoding(column):
    le = LabelEncoder()
    data[column] = le.fit_transform(data[column])

In [22]:
encoding('CarName')

In [23]:
encoding('fueltype')
encoding('aspiration')
encoding('doornumber')
encoding('carbody')
encoding('drivewheel')
encoding('enginelocation')
encoding('enginetype')
encoding('cylindernumber')
encoding('fuelsystem')

In [24]:
data.head()

,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,1,1,0,1,0,2,0,88.6,168.8,...,130,5,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,1,1,0,1,0,2,0,88.6,168.8,...,130,5,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,1,1,0,1,2,2,0,94.5,171.2,...,152,5,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,2,1,0,0,3,1,0,99.8,176.6,...,109,5,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,2,1,0,0,3,0,0,99.4,176.6,...,136,5,3.19,3.40,8.0,115,5500,18,22,17450.0

In [25]:
data.corr()

,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
CarName,1.000000,-0.065597,0.060091,-0.143542,0.053781,-0.007548,0.060707,0.061688,0.057615,-0.033914,...,-0.157652,0.146779,0.201519,-0.201044,0.086201,-0.091439,-0.143058,0.053777,0.055715,-0.173728
fueltype,-0.065597,1.000000,-0.401397,0.191491,-0.147853,-0.132257,0.040070,-0.308346,-0.212679,-0.233880,...,-0.069594,0.041529,-0.054451,-0.241829,-0.984356,0.163926,0.476883,-0.255963,-0.191392,-0.105679
aspiration,0.060091,-0.401397,1.000000,-0.031792,0.063028,0.066465,-0.057191,0.257611,0.234539,0.300567,...,0.108217,0.288086,0.212614,0.222982,0.295541,0.241685,-0.183383,-0.202362,-0.254416,0.177926
doornumber,-0.143542,0.191491,-0.031792,1.000000,-0.680358,0.098954,0.137757,-0.447357,-0.398568,-0.207168,...,-0.020742,0.015519,-0.119258,0.011082,-0.177888,0.126947,0.247668,0.012417,0.036330,-0.031835
carbody,0.053781,-0.147853,0.063028,-0.680358,1.000000,-0.155745,-0.277009,0.401362,0.334433,0.131710,...,-0.073352,-0.065079,0.010549,-0.015325,0.136243,-0.153928,-0.109643,0.031697,-0.007170,-0.083976
drivewheel,-0.007548,-0.132257,0.066465,0.098954,-0.155745,1.000000,0.147865,0.459745,0.485649,0.470751,...,0.524307,0.424686,0.481827,0.071591,0.127479,0.518686,-0.039417,-0.449581,-0.452220,0.577992
enginelocation,0.060707,0.040070,-0.057191,0.137757,-0.277009,0.147865,1.000000,-0.187790,-0.050989,-0.051698,...,0.196826,0.105971,0.185042,-0.138455,-0.019762,0.317839,0.198461,-0.153487,-0.102026,0.324973
wheelbase,0.061688,-0.308346,0.257611,-0.447357,0.401362,0.459745,-0.187790,1.000000,0.874587,0.795144,...,0.569329,0.384601,0.488750,0.160959,0.249786,0.353294,-0.360469,-0.470414,-0.544082,0.577816
carlength,0.057615,-0.212679,0.234539,-0.398568,0.334433,0.485649,-0.050989,0.874587,1.000000,0.841118,...,0.683360,0.557810,0.606454,0.129533,0.158414,0.552623,-0.287242,-0.670909,-0.704662,0.682920
carwidth,-0.033914,-0.233880,0.300567,-0.207168,0.131710,0.470751,-0.051698,0.795144,0.841118,1.000000,...,0.735433,0.521434,0.559150,0.182942,0.181129,0.640732,-0.220012,-0.642704,-0.677218,0.759325
carheight,0.158837,-0.284631,0.087311,-0.552208,0.568534,-0.019719,-0.106234,0.589435,0.491029,0.279210,...,0.067149,0.017046,0.171071,-0.055307,0.261214,-0.108802,-0.320411,-0.048640,-0.107358,0.119336
curbweight,-0.026969,-0.217275,0.324902,-0.197379,0.128467,0.575111,0.050468,0.776386,0.877728,0.867032,...,0.850594,0.611642,0.648480,0.168790,0.151362,0.750739,-0.266243,-0.757414,-0.797465,0.835305
enginetype,-0.163265,0.082695,-0.102963,0.062431,-0.037024,-0.116823,0.114127,-0.135577,-0.113291,0.012298,...,0.040766,-0.091787,0.029355,-0.141918,-0.071873,0.010301,0.005599,-0.085004,-0.078456,0.049171
cylindernumber,0.008118,0.110617,-0.133119,0.154322,-0.048408,0.223238,0.135541,-0.184596,-0.109585,-0.194074,...,-0.085613,0.011970,-0.032844,-0.050088,-0.064701,0.115612,0.222731,-0.126422,-0.085897,-0.027628
enginesize,-0.157652,-0.069594,0.108217,-0.020742,-0.073352,0.524307,0.196826,0.569329,0.683360,0.735433,...,1.000000,0.514070,0.583774,0.203129,0.028971,0.809769,-0.244660,-0.653658,-0.677470,0.874145
fuelsystem,0.146779,0.041529,0.288086,0.015519,-0.065079,0.424686,0.105971,0.384601,0.557810,0.521434,...,0.514070,1.000000,0.475599,0.088153,-0.100786,0.655638,0.014261,-0.671581,-0.645659,0.526823
boreratio,0.201519,-0.054451,0.212614,-0.119258,0.010549,0.481827,0.185042,0.488750,0.606454,0.559150,...,0.583774,0.475599,1.000000,-0.055909,0.005197,0.573677,-0.254976,-0.584532,-0.587012,0.553173
stroke,-0.201044,-0.241829,0.222982,0.011082,-0.015325,0.071591,-0.138455,0.160959,0.129533,0.182942,...,0.203129,0.088153,-0.055909,1.000000,0.186110,0.080940,-0.067964,-0.042145,-0.043931,0.079443
compressionratio,0.086201,-0.984356,0.295541,-0.177888,0.136243,0.127479,-0.019762,0.249786,0.158414,0.181129,...,0.028971,-0.100786,0.005197,0.186110,1.000000,-0.204326,-0.435741,0.324701,0.265201,0.067984
horsepower,-0.091439,0.163926,0.241685,0.126947,-0.153928,0.518686,0.317839,0.353294,0.552623,0.640732,...,0.809769,0.655638,0.573677,0.080940,-0.204326,1.000000,0.131073,-0.801456,-0.770544,0.808139
peakrpm,-0.143058,0.476883,-0.183383,0.247668,-0.109643,-0.039417,0.198461,-0.360469,-0.287242,-0.220012,...,-0.244660,0.014261,-0.254976,-0.067964,-0.435741,0.131073,1.000000,-0.113544,-0.054275,-0.085267
citympg,0.053777,-0.255963,-0.202362,0.012417,0.031697,-0.449581,-0.153487,-0.470414,-0.670909,-0.642704,...,-0.653658,-0.671581,-0.584532,-0.042145,0.324701,-0.801456,-0.113544,1.000000,0.971337,-0.685751
highwaympg,0.055715,-0.191392,-0.254416,0.036330,-0.007170,-0.452220,-0.102026,-0.544082,-0.704662,-0.677218,...,-0.677470,-0.645659,-0.587012,-0.043931,0.265201,-0.770544,-0.054275,0.971337,1.000000,-0.697599
price,-0.173728,-0.105679,0.177926,-0.031835,-0.083976,0.577992,0.324973,0.577816,0.682920,0.759325,...,0.874145,0.526823,0.553173,0.079443,0.067984,0.808139,-0.085267,-0.685751,-0.697599,1.000000

In [26]:
numerical_cols = data.select_dtypes(exclude=['object']).columns

In [27]:
data[numerical_cols].head()

,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,1,0,1,0,2,0,88.6,168.8,64.1,...,130,5,3.47,2.68,9.0,111,5000,21,27,13495.0
1,1,1,0,1,0,2,0,88.6,168.8,64.1,...,130,5,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,1,0,1,2,2,0,94.5,171.2,65.5,...,152,5,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,1,0,0,3,1,0,99.8,176.6,66.2,...,109,5,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,1,0,0,3,0,0,99.4,176.6,66.4,...,136,5,3.19,3.40,8.0,115,5500,18,22,17450.0

In [28]:
X = data.drop(['price'],axis=1)
y = data['price']

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1)

In [30]:
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X_train,y_train)

LinearRegression()

In [31]:
pred=lm.predict(X_test)

In [32]:
pred

array([ 7212.39165719,  6356.4781147 ,  5827.26375609,  5261.33861369,
        8242.90487729, 26976.33453058,  8808.49735517,  -834.82719493,
        7268.37593803, 11065.09695638, 16250.48870144, 15118.22577723,
       15059.09204687, 10252.41011071, 14896.45377114, 13216.80355275,
        7400.29835833,  8894.78686001, 14169.53189717,  9615.51419642,
        8709.19235802,  7553.98226779, 13656.22257101,  7743.49727698,
       11955.19316135,  8934.78742342, 14432.69232675,  8776.99057244,
        7469.99806985,  8878.03709444,  5261.86612733, 11901.79804653,
       23985.04275154,  8962.44119539, 19625.09373215,  7265.87740454,
        7905.81384429, 29942.7549976 ,  9915.19948352, 19023.19459637,
        7130.79120891, 22279.92041694,  6579.97266849,  8946.74553684,
        9070.11144606,  7186.31691974, 40928.79953039,  6345.12921322,
       20028.39376422, 20941.29933759, 26898.70551119, 16684.10570168,
       18800.36112548,  6474.9469879 , 10291.67228128,  6537.38255952,
        9953.57259316, 10140.38371714, 19544.51563254,  6290.97324393,
        8229.36239578,  9121.77107697])

In [33]:
y_test

78      6669.0
97      7999.0
151     6338.0
44      8916.5
40     10295.0
        ...
39      8845.0
110    13860.0
164     8238.0
56     11845.0
176    10898.0
Name: price, Length: 62, dtype: float64

In [34]:
lm.score(X_test,y_test)

0.8104421677670427